[package]
name = "git-historian"
version = "0.1.0"
authors = ["Matt Kline <matthew.kline@flukenetworks.com>"]

[lib]
path = "src/lib.rs"

[[bin]]
name = "git-historian"
path = "src/main.rs"
doc = false

[dependencies]
git2 = "0.4.3"
time = "0.1"
