[package]
name = "git-historian"
version = "0.2.0"
authors = ["Matt Kline <matthew.kline@flukenetworks.com>"]
license = "GPL-2.0"

[lib]
path = "src/lib.rs"

[[bin]]
name = "git-historian"
path = "src/main.rs"
doc = false

[dependencies]
time = "0.1"
